name: cv
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_zoom_drawer: ^3.1.1
  flutter_screenutil: ^5.9.0
  percent_indicator: ^4.2.3
  cupertino_icons: ^1.0.2
  readmore: ^2.2.0
  lottie: ^2.6.0
  get: ^4.6.6
  awesome_icons: ^1.1.0

flutter_launcher_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/

  fonts:
   - family: Times
     fonts:
       - asset: assets/fonts/TimesNewRoman.ttf
